RES=C:\raylib\raylib\src\raylib.rc.data
MINGW_INCLUDE=C:\raylib\w64devkit\x86_64-w64-mingw32\include
MINGW_LIB=C:\raylib\w64devkit\x86_64-w64-mingw32\lib
RAYLIB_SRC=C:\raylib\raylib\src
FLAGS=-std=c99 -Wall 
LIBS=-lraylib -lgdi32 -lwinmm -lopengl32

main: compile
	.\main.exe

compile: main.c
	gcc -o main.exe main.c $(RES) -I. -I$(RAYLIB_SRC) -I$(MINGW_INCLUDE) -L$(MINGW_LIB) -L$(RAYLIB_SRC) $(FLAGS) $(LIBS)

clean:
	rm main.exe
